// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me: dynamic(() => import("./AboutMe")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  work: dynamic(() => import("./Work")),
};
